# To enable nouse activity inside tmux
# set -g mouse on

# To enable vi keybinding in tmux to nevigate around.
setw -g mode-keys vi

# To copy the selected text to the clipboard.
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -se c"
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -se c"
